data:
    dataset: "RainDrop"
    image_size: 32
    channels: 3
    num_workers: 1
    data_dir: "D:\\thang\\20221\\deeplearning\\DDPM"
    result_dir: "D:\\thang\\20221\\deeplearning\\Group16\\result"
    conditional: True

model:
    name: "DDPM"
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 100

training:
    num_batch: 860
    patch_n: 32
    batch_size: 1
    n_epochs: 20000
    n_iters: 2000000
    snapshot_freq: 860
    validation_freq: 860

sampling:
    batch_size: 1
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
